### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by pretech86** [charles-d-burton/kanscan#1]
sorry i'm a beginner , how can use this project , i copy the files to nmap folder and it give me results is it true ?

**Comment by charles-d-burton** [comment]
No, this project is really intended to be on a Kubernetes cluster.   It's more meant to be an API through which you can request scans of hosts.

**Comment by charles-d-burton** [comment]
Setup is pretty easy though.  If you have a kubernetes cluster you just need nats and nats-streaming running in the default namespace.  Then you can just deploy the kustomize template in the argocd directory.  Should fire right up.
